apps/user_management/models.py
from flask import abort
from flask_login import UserMixin, current_user
from werkzeug.security import generate_password_hash, check_password_hash

from apps.app import db, login_manager

from datetime import datetime


# db.Modelを継承してUserクラスの作成を行う
class User(db.Model, UserMixin):
    # テーブル名
    __tablename__ = "users"

    # カラムを定義
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String, index=True)
    email = db.Column(db.String, unique=True, index=True)
    password_hash = db.Column(db.String)
    created_at = db.Column(db.DateTime, default=datetime.now)
    updated_at = db.Column(db.DateTime, default=datetime.now, onupdate=datetime.now)
    is_admin = db.Column(db.Boolean, default=False)  # 管理者フラグ

    # パスワードをセットするためのプロパティ
    @property
    def password(self):
        raise AttributeError("読み取り不可")

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    # パスワードをチェックする
    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)

    # メールアドレス重複チェックをする
    def is_duplicate_email(self):
        return User.query.filter_by(email=self.email).first() is not None


# ログインしているユーザー情報を取得する関数
@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)

apps/user_management/forms.py
from flask_wtf import FlaskForm
from wtforms import PasswordField, StringField, SubmitField
from wtforms.validators import DataRequired, Email, length


# ユーザー新規作成フォーム
class UserForm(FlaskForm):
    username = StringField(
        "ユーザー名",
        validators=[
            DataRequired(message="ユーザー名は必須です。"),
            length(max=30, message="30文字以内で入力してください、"),
        ],
    )

    email = StringField(
        "メールアドレス",
        validators=[
            DataRequired(message="メールアドレスは必須です。"),
            Email(message="メールアドレスの形式で入力してください。"),
        ],
    )

    password = PasswordField("パスワード", validators=[DataRequired(message="パスワードは必須です。")])

    submit = SubmitField("新規登録")


# 管理画面へのログインフォーム
class AdminLoginForm(FlaskForm):
    email = StringField(
        "メールアドレス",
        validators=[DataRequired("メールアドレスは必須です。"), Email("メールアドレスの形式で入力してください。")],
    )

    password = PasswordField("パスワード", validators=[DataRequired("パスワードは必須です。")])

    submit = SubmitField("ログイン")

apps/user_management/__init__.py
import apps.user_management.models

apps/user_management/views.py
from flask import Blueprint, render_template, redirect, url_for
from flask_login import login_required, login_user
from apps.app import db
from apps.user_management.models import User
from apps.user_management.forms import UserForm, AdminLoginForm

from .utils import admin_required

# user_managementアプリの作成
user_management = Blueprint(
    "user_management",
    __name__,
    template_folder="templates",
    static_folder="static",
)


# ユーザーの一覧
@user_management.route("/")
@login_required
@admin_required
def index():
    users = User.query.all()
    return render_template("user_management/index.html", users=users)


# ユーザーの新規作成
@user_management.route("/new", methods=["GET", "POST"])
@login_required
@admin_required
def create_user():
    form = UserForm()
    # フォームの値をバリデート
    if form.validate_on_submit():
        # ユーザーの作成
        user = User(
            username=form.username.data,
            email=form.email.data,
            password=form.password.data,
        )
        # ユーザーを追加してコミットする
        db.session.add(user)
        db.session.commit()
        # ユーザーの一覧画面へリダイレクト
        return redirect(url_for("user_management.index"))
    return render_template("user_management/create.html", form=form)


# ユーザー編集画面
@user_management.route("/edit/<user_id>", methods=["GET", "POST"])
@login_required
@admin_required
def edit_user(user_id):
    form = UserForm()

    user = User.query.filter_by(id=user_id).first()

    # formからサブミットされた場合はユーザーを更新して一覧画面へリダイレクト
    if form.validate_on_submit():
        user.username = form.username.data
        user.email = form.email.data
        user.password = form.password.data
        db.session.add(user)
        db.session.commit()
        return redirect(url_for("user_management.index"))

    return render_template("user_management/edit.html", user=user, form=form)


# ユーザーの削除処理を行うエンドポイント(Postのみ)
@user_management.route("/edit/<user_id>/delete", methods=["POST"])
@login_required
@admin_required
def delete_user(user_id):
    user = User.query.filter_by(id=user_id).first()
    db.session.delete(user)
    db.session.commit()
    return redirect(url_for("user_management.index"))

apps/user_management/templates/user_management/base.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('user_management.static', filename='style.css') }}">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <!-- ナビゲーションバー -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <div class="container">
            <a class="navbar-brand" href="{{ url_for('user_management.index') }}"><b>管理者画面</b></a>
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <span class="nav-link">{{ current_user.username }}</span>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('classify.index') }}">H2_AI</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth.logout') }}">ログアウト</a>
                </li>
            </ul>
        </div>
    </nav>

    <section class="container">
    {% block content %}{% endblock %}
    </section>
    {% block endbody %}{% endblock %}
</body>
</html>

apps/user_management/templates/user_management/create.html
{% extends "user_management/base.html" %}

{% block title %}ユーザー新規作成{% endblock %}

{% block content %}
<h2>ユーザー新規作成</h2>
<form 
    action="{{ url_for('user_management.create_user') }}"
    method="POST"
    novalidate="novalidate"
>
    {{ form.csrf_token }}
    <p>
        {{ form.username.label }} {{ form.username(placeholder="ユーザー名") }}
    </p>
    {% for error in form.username.errors %}
    <span style="color: red;">{{ error }}</span>
    {% endfor %}

    <p>
        {{ form.email.label }} {{ form.email(placeholder="メールアドレス") }}
    </p>
    {% for error in form.email.errors %}
    <span style="color: red;">{{ error }}</span>
    {% endfor %}

    <p>
        {{ form.password.label }} {{ form.password(placeholder="ユーザー名") }}
    </p>
    {% for error in form.password.errors %}
    <span style="color: red;">{{ error }}</span>
    {% endfor %}
    <p>{{ form.submit() }}</p>
</form>
{% endblock %}

apps/user_management/templates/user_management/edit.html
{% extends "user_management/base.html" %}

{% block title %}ユーザー編集{% endblock %}

{% block content %}
<h2>ユーザー編集</h2>
<form 
    action="{{ url_for('user_management.edit_user', user_id=user.id) }}"
    method="POST"
    novalidate="novalidate"
>
    {{ form.csrf_token }}

    <p>
        {{ form.username.label }} {{ form.username(placeholder="ユーザー名", value=user.username) }}
    </p>
    {% for error in form.username.errors %}
    <span style="color: red;">{{ error }}</span>
    {% endfor %}

    <p>
        {{ form.email.label }} {{ form.email(placeholder="メールアドレス", value=user.email) }}
    </p>
    {% for error in form.email.errors %}
    <span style="color: red;">{{ error }}</span>
    {% endfor %}

    <p>
        {{ form.password.label }} {{ form.password(placeholder="パスワード") }}
    </p>
    {% for error in form.password.errors %}
    <span style="color: red;">{{ error }}</span>
    {% endfor %}

    <p><input type="submit" value="更新"></p>
</form>

<form action="{{ url_for('user_management.delete_user', user_id=user.id) }} " method="POST">
    {{ form.csrf_token }}
    <input type="submit" value="削除">
</form>


{% endblock %}

apps/user_management/templates/user_management/index.html
{% extends "user_management/base.html" %}

{% block title %}ユーザーの一覧{% endblock %}

{% block content %}
<h2>ユーザーの一覧</h2>

<a href="{{ url_for('user_management.create_user') }}">ユーザー新規作成</a>

<table>
    <tr>
        <th>ユーザーID</th>
        <th>ユーザー名</th>
        <th>メールアドレス</th>
    </tr>
    {% for user in users %}
    <tr>
        <td><a href="{{ url_for('user_management.edit_user', user_id=user.id) }}">{{ user.id }}</a></td>
        <td>{{ user.username }}</td>
        <td>{{ user.email }}</td>
    </tr>
    {% endfor %}
</table>
{% endblock %}

apps/user_management/templates/user_management/login.html
{% extends "user_management/base/html" %}

{% block title %}管理者ページログイン{% endblock %}

{% block content %}
<div class="mx-auto usm-main">
    <div class="card usm-login">
        <header>管理者ログイン</header>
        <section>
            <form 
                action="{{ url_for('user_management.login') }}"
                method="POST"
                novalidate="novalidate"
            >
                {{ form.csrf_token }}

                {% for message in get_flashed_messages() %}
                <span class="usm-flash">{{ message }}</span>
                {% endfor %}

                {{ from.email(class="form-control usm-input", placeholder="メールアドレス") }}

                {{ form.password(class="form-control usm-input", placeholder="パスワード") }}

                {{ form.submit(class="btn btn-md btn-dark btn-block usm-btn") }}
            </form>
        </section>
    </div>
</div>
{% endblock %}