apps/classify/models.py
from datetime import datetime

from apps.app import db

apps/classify/views.py
from flask import Blueprint, render_template, request, jsonify
from flask_login import login_required

import numpy as np
import base64
import cv2

import datetime
import re

from .mnist.predict import predict

# classifyアプリ
classify = Blueprint(
    "classify", __name__, template_folder="templates", static_folder="static"
)


# indexエンドポイント
@classify.route("/")
def index():
    return render_template("classify/index.html")


# digitsdrawエンドポイントの作成
@classify.route("/digitsdraw", methods=["GET", "POST"])
@login_required
def digitsdraw():
    # POSTされた場合
    if request.method == "POST":
        prediction = get_digits_predict(request)
        return jsonify({"prediction": prediction})

    # GET処理だった場合
    else:
        return render_template("classify/digitsdraw.html")


# 予測結果を返す関数
def get_digits_predict(req: request):
    # DataURLからデータ部分だけを抽出
    img_str = re.search(r"base64,(.*)", req.form["img"]).group(1)

    # base64モジュールを利用してndarray配列へ変換
    np_arr = np.fromstring(base64.b64decode(img_str), np.uint8)

    # opencv画像として読み込む
    img_src = cv2.imdecode(np_arr, cv2.IMREAD_COLOR)

    # 色の反転
    img_negaposi = 255 - img_src

    # グレースケールに変換
    img_gray = cv2.cvtColor(img_negaposi, cv2.COLOR_BGR2GRAY)

    # (28, 28)にリサイズ
    img_resize = cv2.resize(img_gray, (28, 28))

    pred: int = predict(img_resize)

    return pred

apps/classify/templates/classify/base.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('classify.static', filename='css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('classify.static', filename='css/style.css') }}">
    <title>{% block title %}{% endblock %}</title>
</head>

<body>
    <!-- ナビゲーションバー -->
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="{{ url_for('classify.index') }}"><b>H2_AI</b></a>
            <button 
                class="navbar-toggler ml-auto"
                type="button"
                data-toggle="collapse"
                data-target="#clf-navbar"
                aria-controls="clf-navbar"
                aria-expanded="false"
                aria-label="Toggle navigation"
            >
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="clf-navbar">
                <div class="navbar-nav ml-auto">
                    {% if current_user.is_authenticated and current_user.is_admin %}
                    <li class="nav-item">
                        <a class="nav-link" href="#">{{ current_user.username }}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('user_management.index') }}">管理者画面</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('auth.logout') }}">ログアウト</a>
                    </li>
                    {% elif current_user.is_authenticated %}
                    <li class="nav-item">
                        <span class="nav-link">{{ current_user.username }}</span>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('auth.logout') }}">ログアウト</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('auth.signup') }}">新規登録</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('auth.login') }}">ログイン</a>
                    </li>
                    {% endif %}
                </div>
            </div>
        </div>
    </nav>
    <section class="container">
    {% block content %}{% endblock %}
    </section>
    <script src="{{ url_for('classify.static', filename='js/jquery-3.7.1.min.js') }}"></script>
    <script src="{{ url_for('classify.static', filename='js/toggle.js') }}"></script>
    {% block endbody %}{% endblock %}
</body>
</html>

apps/classify/templates/classify/digitsdraw.html
{% extends "classify/base.html" %}

{% block title %}手書き数字認識AI{% endblock %}

{% block content %}
<h4>手書き数字認識(0-9)</h4>

<div class="canvasdiv" id="canv">
    <canvas id="can" width="280px" height="280px"></canvas>
</div>

<div class="dg-btn">
    <button type="submit" class="btn btn-dark canv-clear" onclick="sendImage();">予測</button>
    <span id="dg-ans"></span>
</div>

<div class="dg-btn">
    <button type="submit" class="btn btn-dark canv-clear" onclick="clearCanv();">クリア処理</button>
</div>

{% endblock %}

{% block endbody %}
<script src="{{ url_for('classify.static', filename='js/canv.js') }}"></script>
{% endblock %}

apps/classify/templates/classify/index.html
{% extends "classify/base.html" %}

{% block title %}分類モデル{% endblock %}

{% block content %}
{% for message in get_flashed_messages() %}
<div class="alert alert-danger my-4" role="alert">{{ message }}</div>
{% endfor %}
<h2 class="mt-3">分類モデル</h2>
<div class="card-group">
    <div class="row">
        <div class="col-10 col-md-6 justify-content-center align-items-start">
            <div class="card m-2" id="digitsdraw">
                <img class="card-img-top" src="{{ url_for('classify.static', filename='image/mnist_image.png') }}" alt="mnist画像">
                <div class="card-body">
                    <h5 class="card-title"><a href="{{ url_for('classify.digitsdraw') }}">手書き文字認識</a></h5>
                    <p class="card-text">手書きで文字を入力してAIに予測させてみよう！</p>
                </div>
            </div>
        </div>
        <div class="col-10 col-md-6 justify-content-center align-items-start">
            <div class="card m-2">
                <div class="card-body">
                    <h5 class="card-title">準備中...</h5>
                    <p class="card-text">準備中...</p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}